version: '3'
services:
  frontend:
    image: your_frontend_image:latest
    ports:
      - 3000:3000

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw123
      - POSTGRES_DB=autoavenue-database
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://autoavenue-backend-postgres-1:5432/autoavenue-database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pw123

volumes:
  postgres-data:
